INSERT INTO TBG_TUTOR (ID_TUTOR, DE_NOMBRE, DE_APELLIDOS) VALUES (SEQ_TUTOR.nextval, 'Carlos', 'Alonso González');
INSERT INTO TBG_TUTOR (ID_TUTOR, DE_NOMBRE, DE_APELLIDOS) VALUES (SEQ_TUTOR.nextval, 'Perico', 'Palotes');

INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR) VALUES (SEQ_CURSO.nextval, 1, 'Curso 1', 'BASICO', 20, 1);
INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR) VALUES (SEQ_CURSO.nextval, 1, 'Curso 2', 'INTERMEDIO', 40, 1);
INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR) VALUES (SEQ_CURSO.nextval, 1, 'Curso 3', 'INTERMEDIO', 60, 2);
INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR) VALUES (SEQ_CURSO.nextval, 1, 'Curso 3', 'AVANZADO', 120, 1);