INSERT INTO TBG_TUTOR (ID_TUTOR, DE_NOMBRE, DE_APELLIDOS) VALUES (SEQ_TUTOR.nextval, 'Carlos', 'Alonso González');
INSERT INTO TBG_TUTOR (ID_TUTOR, DE_NOMBRE, DE_APELLIDOS) VALUES (SEQ_TUTOR.nextval, 'Perico', 'Palotes');

INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR, DE_TEMARIO) VALUES (SEQ_CURSO.nextval, 1, 'Curso 1', 'BASICO', 20, 1, 'ember.js_application_development_how-to.pdf');
INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR, DE_TEMARIO) VALUES (SEQ_CURSO.nextval, 1, 'Curso 2', 'INTERMEDIO', 40, 1, 'ember.js_application_development_how-to.pdf');
INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR, DE_TEMARIO) VALUES (SEQ_CURSO.nextval, 1, 'Curso 3', 'INTERMEDIO', 60, 2, 'ember.js_in_action_ch1.pdf');
INSERT INTO TBG_CURSO (ID_CURSO, LG_ACTIVO, DE_TITULO, DE_NIVEL, NU_HORAS, ID_TUTOR) VALUES (SEQ_CURSO.nextval, 1, 'Curso 4', 'AVANZADO', 120, 1);